[workspace]
resolver = "2"
members = [
    "crates/stt-core",
    "crates/stt-platform",
    "crates/stt-config",
    "crates/stt-metadata",
    "crates/stt-hook",
    "crates/stt-steamui",
    "crates/stt-steamclient",
    "crates/stt-host",
    "crates/stt-loader-dwmapi",
    "crates/stt-loader-xinput",
]
default-members = [
    "crates/stt-core",
    "crates/stt-platform",
    "crates/stt-config",
    "crates/stt-metadata",
    "crates/stt-hook",
    "crates/stt-steamui",
    "crates/stt-steamclient",
    "crates/stt-host",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "local"
publish = false

[workspace.dependencies]
stt-core = { path = "crates/stt-core" }
stt-platform = { path = "crates/stt-platform" }
stt-config = { path = "crates/stt-config" }
stt-metadata = { path = "crates/stt-metadata" }
stt-hook = { path = "crates/stt-hook" }
stt-steamui = { path = "crates/stt-steamui" }
stt-steamclient = { path = "crates/stt-steamclient" }

[workspace.lints.rust]
nonstandard_style = { level = "deny", priority = -2 }
unused = { level = "deny", priority = -2 }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
