//! catalog_add: AddToLibrary 意图路径 (Mock/真源共用).

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use stt_catalog::{validate_bundle, CatalogProvider, CatalogTraceEntry};
use stt_core::{AppId, CatalogBundle, DepotId};
use stt_platform::WinHttpGetOptions;

use crate::catalog_dlc::{expand_dlcs, DlcExpandOptions, DlcExpandReport};
use crate::error::{ConfigError, Result};
use crate::lua_load::default_lua_dir;
use crate::tools::ToolId;
use crate::ConfigState;

/// 一次入库意图的结果 (成功 = 元数据已进 core 且 lua 已落盘).
#[derive(Debug, Clone)]
pub struct AddToLibraryOutcome {
    pub app_id: AppId,
    pub provider_id: String,
    pub provider_trace: Vec<CatalogTraceEntry>,
    pub lua_path: PathBuf,
    pub epoch: u64,
    pub owned_count: usize,
    /// 入库成功后仍缺的下载数据 (有清单但缺 key/token), 空 = 齐全.
    pub missing: MissingDownloadData,
    /// 写入 depotcache 的原始 .manifest 文件数 (0 = 源没给字节, 不失败).
    pub manifest_files_written: usize,
    /// 本次并入的 DLC (仅解锁 / 可下载); 关 auto_dlc 时为空.
    pub dlc: DlcExpandReport,
    /// 最终 bundle 里全部 owned app (主 + DLC), 供 package0 注入.
    pub owned_apps: Vec<AppId>,
}

/// 下载数据缺失情况 (Steam 拿不到就下不了, 应该提示用户).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MissingDownloadData {
    /// 只有清单 (manifest) 没拿到下载密钥 (depot key) 的 depot, 升序.
    pub depot_keys: Vec<DepotId>,
    /// 有清单但缺 access token (下载 0B 的常见原因).
    pub access_token: bool,
}

impl MissingDownloadData {
    /// 全部数据齐了, 不需要提示.
    pub fn is_empty(&self) -> bool {
        self.depot_keys.is_empty() && !self.access_token
    }

    /// 人类可读的缺失描述, 空串 = 齐全.
    pub fn describe(&self) -> String {
        let mut parts = Vec::new();
        if !self.depot_keys.is_empty() {
            let ids: Vec<String> = self.depot_keys.iter().map(u32::to_string).collect();
            parts.push(format!("下载密钥 (Depot {})", ids.join(", ")));
        }
        if self.access_token {
            parts.push("访问令牌".to_owned());
        }
        parts.join("、")
    }
}

/// 合法 depot decryption key: 正好 64 位 ascii hex.
pub fn is_valid_depot_key(key: &str) -> bool {
    key.len() == 64 && key.bytes().all(|b| b.is_ascii_hexdigit())
}

/// 从可下载集合里摘掉「有清单/已声明但没有合法 key」的 depot.
///
/// 背景: steamcmd 会把 DLC 关联 depot (带 dlcappid) 也挂到主 app 的 depots 上.
/// 若上游没有这些 DLC 仓的 key, 仍写进 `setappdepots` / 空 key 的 `addappid`,
/// Steam 会把**整包**判成加密 (「内容仍然处于加密状态」), 主游戏有 key 也下不了.
///
/// 策略: 无 key 的 depot 不进入下载面; DLC **所有权** (apps 里的 dlc appid) 保留.
/// 返回被摘掉的 depot id (诊断用).
pub fn prune_keyless_depots(bundle: &mut CatalogBundle) -> Vec<DepotId> {
    // 先清掉非法/空 key 条目.
    bundle.depot_keys.retain(|_, key| is_valid_depot_key(key));

    let mut dropped: Vec<DepotId> = Vec::new();
    for depots in bundle.app_depots.values_mut() {
        for depot_id in depots.iter().copied() {
            if !bundle.depot_keys.contains_key(&depot_id) {
                dropped.push(depot_id);
            }
        }
        depots.retain(|depot_id| bundle.depot_keys.contains_key(depot_id));
    }

    // 没 key 的清单不要 pin, 否则 Steam 仍可能去拉加密仓.
    bundle
        .manifests
        .retain(|depot_id, _| bundle.depot_keys.contains_key(depot_id));

    dropped.sort_unstable();
    dropped.dedup();
    dropped
}

/// 算 bundle 里缺的下载数据 (只算请求 app 的).
///
/// 判定:
/// - depot key: 该 depot 仍挂在 app_depots 且有 manifest, 但没有合法 depot key.
///   调用方应先 [`prune_keyless_depots`], 这样 DLC 仓缺 key 不会误报成主游戏不可下.
/// - access token: 有清单但没给 token, Steam 下载授权过不去 (常见表现为下载 0B).
pub fn missing_download_data(app_id: AppId, bundle: &CatalogBundle) -> MissingDownloadData {
    let app_depots = bundle.app_depots.get(&app_id);
    let mut depot_keys: Vec<DepotId> = app_depots
        .into_iter()
        .flatten()
        .copied()
        .filter(|depot_id| {
            bundle.manifests.contains_key(depot_id)
                && !bundle
                    .depot_keys
                    .get(depot_id)
                    .is_some_and(|k| is_valid_depot_key(k))
        })
        .collect();
    depot_keys.sort_unstable();
    let has_manifest = app_depots
        .into_iter()
        .flatten()
        .any(|depot_id| bundle.manifests.contains_key(depot_id));
    // 源明确说不需要 token (steamcmd `_missing_token: false`) 时不报缺 token.
    let need_token = bundle.requires_token != Some(false);
    MissingDownloadData {
        depot_keys,
        // token 为 0 等于没有 (上游用 0 表示未收录).
        access_token: has_manifest
            && need_token
            && bundle.access_tokens.get(&app_id).copied().unwrap_or(0) == 0,
    }
}

/// 将 bundle 写成兼容上游的 lua 片段.
pub fn format_catalog_lua(app_id: AppId, bundle: &CatalogBundle) -> String {
    let mut out = String::from("-- generated by SteamTools catalog_add\n");
    let mut apps = bundle.apps.clone();
    apps.sort_unstable();
    apps.dedup();
    for id in apps {
        let purchase_time = bundle.purchase_times.get(&id).copied().unwrap_or(0);
        out.push_str(&format!("addappid({id}, {purchase_time})\n"));
    }

    let mut depots: Vec<_> = bundle.app_depots.values().flatten().copied().collect();
    depots.sort_unstable();
    depots.dedup();
    for depot_id in depots {
        // 无合法 key 的 depot 不写 (空 key 会让 Steam 整包判加密).
        let Some(key) = bundle.depot_keys.get(&depot_id).map(String::as_str) else {
            continue;
        };
        if !is_valid_depot_key(key) {
            continue;
        }
        out.push_str(&format!("addappid({depot_id}, 0, \"{key}\")\n"));
    }
    let mut access_tokens: Vec<_> = bundle.access_tokens.iter().collect();
    access_tokens.sort_unstable_by_key(|(app_id, _)| **app_id);
    for (&id, &token) in access_tokens {
        out.push_str(&format!("addtoken({id}, \"{token}\")\n"));
    }
    let mut manifests: Vec<_> = bundle.manifests.iter().collect();
    manifests.sort_unstable_by_key(|(depot_id, _)| **depot_id);
    for (&depot, over) in manifests {
        // 第三参 size 必须写出: 否则 hook 侧 size=0, 安装对话框显示 0B
        // (OpenSteamTool: setManifestid(depot, gid, size); size 默认 0 会保留原值,
        // 但假 license 路径原值常是 0, 必须把 steamcmd download/size 灌进去).
        if over.size != 0 {
            out.push_str(&format!(
                "setmanifestid({depot}, \"{}\", {})\n",
                over.manifest_gid, over.size
            ));
        } else {
            out.push_str(&format!(
                "setmanifestid({depot}, \"{}\")\n",
                over.manifest_gid
            ));
        }
    }
    let mut app_depots: Vec<_> = bundle.app_depots.iter().collect();
    app_depots.sort_unstable_by_key(|(id, _)| **id);
    for (&id, depots) in app_depots {
        let mut depots = depots.clone();
        depots.sort_unstable();
        depots.dedup();
        let values = depots
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "if type(setappdepots) == \"function\" then setappdepots({id}, {{{values}}}) end\n"
        ));
    }
    debug_assert!(bundle.apps.contains(&app_id));
    out
}

pub fn catalog_lua_path(steam_root: &Path, app_id: AppId) -> PathBuf {
    default_lua_dir(steam_root).join(format!("stt_{app_id}.lua"))
}

/// 写入 `<Steam>/config/lua/stt_{app_id}.lua`.
pub fn write_catalog_lua(
    steam_root: &Path,
    app_id: AppId,
    bundle: &CatalogBundle,
) -> Result<PathBuf> {
    let dir = default_lua_dir(steam_root);
    std::fs::create_dir_all(&dir).map_err(|source| ConfigError::Io {
        path: dir.clone(),
        source,
    })?;
    let path = catalog_lua_path(steam_root, app_id);
    let body = format_catalog_lua(app_id, bundle);
    crate::intent::write_atomic(&path, &body)?;
    Ok(path)
}

/// 原始 .manifest 文件名: `{depot}_{gid}.manifest` (Fluent / Steam 约定).
pub fn manifest_file_name(depot_id: DepotId, manifest_gid: u64) -> String {
    format!("{depot_id}_{manifest_gid}.manifest")
}

/// 把 archive 给的原始 .manifest 写到两个 depotcache 目录.
///
/// 对齐 Fluent-Install:
/// - `<Steam>/depotcache/{depot}_{gid}.manifest`
/// - `<Steam>/config/depotcache/{depot}_{gid}.manifest`
///
/// 缺 blob 不报错 (request-code hook 仍可在线拉); 单文件写失败计入 0 次成功.
pub fn write_manifest_blobs(
    steam_root: &Path,
    blobs: &[stt_catalog::ManifestBlob],
) -> Result<usize> {
    if blobs.is_empty() {
        return Ok(0);
    }
    let primary = steam_root.join("depotcache");
    let secondary = steam_root.join("config").join("depotcache");
    for dir in [&primary, &secondary] {
        std::fs::create_dir_all(dir).map_err(|source| ConfigError::Io {
            path: dir.clone(),
            source,
        })?;
    }
    let mut written = 0usize;
    for blob in blobs {
        if blob.bytes.is_empty() || blob.depot_id == 0 || blob.manifest_gid == 0 {
            continue;
        }
        let name = manifest_file_name(blob.depot_id, blob.manifest_gid);
        let mut ok_any = false;
        for dir in [&primary, &secondary] {
            let path = dir.join(&name);
            match write_atomic_bytes(&path, &blob.bytes) {
                Ok(()) => ok_any = true,
                Err(_) => {
                    // 单个目录失败不阻断另一目录 / 其它 depot.
                }
            }
        }
        if ok_any {
            written += 1;
        }
    }
    Ok(written)
}

fn write_atomic_bytes(path: &Path, bytes: &[u8]) -> Result<()> {
    use std::ffi::OsString;
    let mut name: OsString = path.file_name().unwrap_or_default().to_owned();
    name.push(".tmp");
    let tmp = path.with_file_name(name);
    std::fs::write(&tmp, bytes).map_err(|source| ConfigError::Io {
        path: tmp.clone(),
        source,
    })?;
    std::fs::rename(&tmp, path).map_err(|source| {
        let _ = std::fs::remove_file(&tmp);
        ConfigError::Io {
            path: path.to_path_buf(),
            source,
        }
    })
}

fn now_unix() -> u32 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .ok()
        .and_then(|d| u32::try_from(d.as_secs()).ok())
        .unwrap_or(0)
}

/// 工具开启时: fetch → (可选 DLC 扩展) → 写 lua → 合并进 ConfigState.
pub fn add_to_library(
    state: &ConfigState,
    steam_root: &Path,
    provider: &dyn CatalogProvider,
    app_id: AppId,
) -> Result<AddToLibraryOutcome> {
    add_to_library_with_dlc(
        state,
        steam_root,
        provider,
        app_id,
        DlcExpandOptions::disabled(),
        WinHttpGetOptions::default(),
    )
}

/// 同 [`add_to_library`], 带 DLC 扩展选项.
pub fn add_to_library_with_dlc(
    state: &ConfigState,
    steam_root: &Path,
    provider: &dyn CatalogProvider,
    app_id: AppId,
    dlc_opts: DlcExpandOptions,
    http: WinHttpGetOptions,
) -> Result<AddToLibraryOutcome> {
    if !state.tools().is_enabled(ToolId::CatalogAdd) {
        return Err(ConfigError::Invalid("catalog_add tool is disabled".into()));
    }

    let fetched = provider.fetch_with_trace(app_id)?;
    let mut bundle = validate_bundle(app_id, fetched.bundle)?;
    let purchase = now_unix();
    bundle.purchase_times.entry(app_id).or_insert(purchase);

    let dlc = expand_dlcs(
        app_id,
        &mut bundle,
        &fetched.related_dlc_ids,
        provider,
        dlc_opts,
        http,
    );
    // 无 key 的 depot (常见: DLC 仓) 不进 setappdepots / setmanifestid,
    // 否则主游戏有 key 也会被 Steam 判「内容仍然处于加密状态」.
    let _pruned = prune_keyless_depots(&mut bundle);
    // 扩展后可能多了 apps/depots, 再校验一次.
    let bundle = validate_bundle(app_id, bundle)?;

    let lua_path = write_catalog_lua(steam_root, app_id, &bundle)?;
    // Fluent 路径: 有原始 .manifest 就写 depotcache; 没有也不挡入库.
    // 已 prune 的 keyless depot 对应 blob 即使源给了也不写, 避免 Steam 去拉加密仓.
    let kept_manifests = &bundle.manifests;
    let filtered_blobs: Vec<stt_catalog::ManifestBlob> = fetched
        .manifest_blobs
        .into_iter()
        .filter(|blob| {
            kept_manifests
                .get(&blob.depot_id)
                .is_some_and(|over| over.manifest_gid == blob.manifest_gid)
        })
        .collect();
    let manifest_files_written =
        write_manifest_blobs(steam_root, &filtered_blobs).unwrap_or(0);

    // 以磁盘 lua 为准重载, 避免 DLC 列表缩小时 merge 残留旧 owned.
    #[cfg(feature = "lua")]
    {
        let _ = state.reload_lua_dirs(steam_root);
    }
    #[cfg(not(feature = "lua"))]
    {
        state.with_rules_mut(|rules| {
            rules.apply_catalog_bundle(&bundle);
        });
    }

    let mut owned_apps: Vec<AppId> = bundle.apps.iter().copied().filter(|&id| id != 0).collect();
    owned_apps.sort_unstable();
    owned_apps.dedup();

    Ok(AddToLibraryOutcome {
        app_id,
        provider_id: fetched.source,
        provider_trace: fetched.trace,
        lua_path,
        epoch: state.rules_epoch(),
        owned_count: state.owned_count(),
        missing: missing_download_data(app_id, &bundle),
        manifest_files_written,
        dlc,
        owned_apps,
    })
}

/// 一次移除的结果.
#[derive(Debug, Clone)]
pub struct RemoveFromLibraryOutcome {
    pub app_id: AppId,
    /// 删掉的 lua; 文件本来就不在时为 `None` (仍算成功).
    pub lua_path: Option<PathBuf>,
    pub epoch: u64,
    pub owned_count: usize,
}

/// 把入库撤掉: 删 `stt_{app_id}.lua`, 然后整表重扫.
///
/// 不去 `AppRules` 里做减法 —— 那份状态是所有 lua 合并出来的, 单独摘一个 app 容易
/// 与磁盘不一致. 删完重扫是唯一能保证两边一致的做法, 而且几十个文件也就几毫秒.
///
/// 只删我们自己写的那个文件; 用户手写的 lua 一概不碰.
#[cfg(feature = "lua")]
pub fn remove_from_library(
    state: &ConfigState,
    steam_root: &Path,
    app_id: AppId,
) -> Result<RemoveFromLibraryOutcome> {
    let path = catalog_lua_path(steam_root, app_id);
    let lua_path = match std::fs::remove_file(&path) {
        Ok(()) => Some(path),
        // 已经不在了: 目的已经达到, 不当错误.
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(ConfigError::Io {
                path: path.clone(),
                source,
            })
        }
    };
    state.reload_lua_dirs(steam_root);
    Ok(RemoveFromLibraryOutcome {
        app_id,
        lua_path,
        epoch: state.rules_epoch(),
        owned_count: state.owned_count(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host_toml::HostConfig;
    use stt_catalog::{CatalogResult, MockCatalogProvider};
    use stt_core::AppRules;

    #[test]
    fn format_lua_contains_addappid_and_key() {
        let mut b = CatalogBundle::default();
        b.apps.push(10);
        b.app_depots.insert(10, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 12345,
            },
        );
        let s = format_catalog_lua(10, &b);
        assert!(s.contains("addappid(11, 0,"));
        assert!(s.contains("setappdepots(10, {11})"));
        assert!(
            s.contains("setmanifestid(11, \"99\", 12345)\n"),
            "size 必须写入, 否则安装对话框 0B: {s}"
        );
    }

    #[test]
    fn format_lua_omits_zero_size_third_arg() {
        let mut b = CatalogBundle::default();
        b.apps.push(10);
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        let s = format_catalog_lua(10, &b);
        assert!(s.contains("setmanifestid(11, \"99\")\n"));
        assert!(!s.contains("setmanifestid(11, \"99\", 0)"));
    }

    /// 默认工具开关下跑一次入库 (tempdir 需与结果同生命周期).
    fn add_app_42() -> (tempfile::TempDir, ConfigState, AddToLibraryOutcome) {
        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();
        let provider = MockCatalogProvider::new()
            .with_auto_generate(true)
            .with_simple_app(42, 43, &"ab".repeat(32), 100);
        let out = add_to_library(&state, root.path(), &provider, 42).unwrap();
        (root, state, out)
    }

    #[test]
    fn writes_lua_with_addappid_line() {
        let (_root, _state, out) = add_app_42();
        let text = std::fs::read_to_string(&out.lua_path).unwrap();
        assert!(text.contains("addappid(42,"), "lua 缺 addappid: {text}");
    }

    #[test]
    fn replaces_existing_lua_atomically_without_leaving_temp_file() {
        let root = tempfile::tempdir().unwrap();
        let path = catalog_lua_path(root.path(), 42);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "old").unwrap();
        let provider = MockCatalogProvider::new()
            .with_auto_generate(true)
            .with_simple_app(42, 43, &"ab".repeat(32), 100);
        let state = ConfigState::new();

        add_to_library(&state, root.path(), &provider, 42).unwrap();

        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("addappid(42,"), "{text}");
        assert!(!path.with_file_name("stt_42.lua.tmp").exists());
    }

    #[test]
    fn marks_app_owned_in_rules() {
        let (_root, state, _out) = add_app_42();
        assert!(state.with_rules(|r: &AppRules| r.is_owned(42)));
        assert!(!state.with_rules(|r: &AppRules| r.is_owned(43)));
    }

    #[test]
    fn keeps_depot_key_from_provider() {
        let (_root, state, _out) = add_app_42();
        assert_eq!(
            state.with_rules(|r: &AppRules| r.depot_key(43).map(str::len)),
            Some(64)
        );
    }

    #[test]
    fn writes_depot_key_with_depot_id() {
        let (_root, _state, out) = add_app_42();
        let text = std::fs::read_to_string(out.lua_path).unwrap();

        assert!(
            text.contains("addappid(43, 0,"),
            "lua 没按 DepotId 写 key: {text}"
        );
    }

    #[test]
    fn lua_round_trip_preserves_app_depot_relationship() {
        let (_root, state, _out) = add_app_42();

        assert_eq!(
            state.with_rules(|rules| rules.app_depots(42).to_vec()),
            vec![43]
        );
    }

    #[test]
    fn format_lua_orders_metadata_by_id() {
        let mut bundle = CatalogBundle::default();
        bundle.apps.push(42);
        bundle.app_depots.insert(42, vec![44, 43]);
        bundle.depot_keys.insert(44, "cd".repeat(32));
        bundle.depot_keys.insert(43, "ab".repeat(32));

        let text = format_catalog_lua(42, &bundle);

        assert!(text.find("addappid(43, 0,") < text.find("addappid(44, 0,"));
    }

    #[test]
    fn bumps_rules_epoch() {
        let (_root, _state, out) = add_app_42();
        assert!(out.epoch > 0);
    }

    #[test]
    fn missing_download_data_flags_manifest_without_key() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11, 12]);
        // depot 11: 有清单无密钥 → 应被标出.
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        // depot 12: 清单 + 密钥都齐 → 不标.
        b.depot_keys.insert(12, "a".repeat(64));
        b.manifests.insert(
            12,
            stt_core::ManifestOverride {
                manifest_gid: 88,
                size: 0,
            },
        );
        // 有清单但没给 token → 标出.
        let missing = missing_download_data(42, &b);
        assert_eq!(missing.depot_keys, vec![11]);
        assert!(missing.access_token);
        assert!(missing.describe().contains("Depot 11"));
        assert!(missing.describe().contains("访问令牌"));
        assert!(!missing.is_empty());
    }

    #[test]
    fn missing_download_data_empty_when_all_keys_and_token_present() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        b.access_tokens.insert(42, 123);
        assert!(missing_download_data(42, &b).is_empty());
    }

    #[test]
    fn missing_download_data_empty_without_manifests() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        // 没有 manifest 就没有"该下但下不了"一说, 不提示.
        assert!(missing_download_data(42, &b).is_empty());
    }

    #[test]
    fn missing_download_data_ignores_other_apps_depots() {
        let mut b = CatalogBundle {
            apps: vec![42, 7],
            ..CatalogBundle::default()
        };
        b.app_depots.insert(42, vec![11]);
        b.app_depots.insert(7, vec![12]);
        // 缺 key 的 depot 12 属于 app 7, 不归这次入库 (app 42) 管.
        b.manifests.insert(
            12,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        // app 42 没有 manifest, token 缺失也不提示.
        assert!(missing_download_data(42, &b).is_empty());
    }

    #[test]
    fn missing_download_data_flags_only_token_when_keys_present() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        // key 齐但没 token → 只报 token (1129580 的真实场景).
        let missing = missing_download_data(42, &b);
        assert!(missing.depot_keys.is_empty());
        assert!(missing.access_token);
        assert_eq!(missing.describe(), "访问令牌");
    }

    #[test]
    fn missing_download_data_skips_token_when_source_marks_it_unneeded() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        b.requires_token = Some(false);

        assert!(missing_download_data(42, &b).is_empty());
    }

    #[cfg(feature = "lua")]
    #[test]
    fn add_to_library_prunes_keyless_depot_from_download_surface() {
        // 只有清单没有 key 的 depot 不再写入 setmanifestid / setappdepots,
        // 避免主游戏被 Steam 整包判加密. 所有权 (addappid 主 app) 仍在.
        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();
        let bundle = CatalogBundle {
            apps: vec![42],
            app_depots: std::collections::HashMap::from([(42, vec![11, 12])]),
            depot_keys: std::collections::HashMap::from([(12, "ab".repeat(32))]),
            manifests: std::collections::HashMap::from([
                (
                    11,
                    stt_core::ManifestOverride {
                        manifest_gid: 99,
                        size: 0,
                    },
                ),
                (
                    12,
                    stt_core::ManifestOverride {
                        manifest_gid: 88,
                        size: 100,
                    },
                ),
            ]),
            requires_token: Some(false),
            ..CatalogBundle::default()
        };
        let provider = MockCatalogProvider::new().with_fixture(42, bundle);

        let outcome = add_to_library(&state, root.path(), &provider, 42).unwrap();
        let text = std::fs::read_to_string(&outcome.lua_path).unwrap();

        assert!(text.contains("addappid(12, 0,"), "{text}");
        assert!(!text.contains("addappid(11,"), "{text}");
        assert!(text.contains("setmanifestid(12,"), "{text}");
        assert!(!text.contains("setmanifestid(11,"), "{text}");
        assert!(text.contains("setappdepots(42, {12})"), "{text}");
        assert!(
            outcome.missing.depot_keys.is_empty(),
            "{:?}",
            outcome.missing
        );
        assert!(text.contains("addappid(42,"), "{text}");
    }

    #[test]
    fn prune_keyless_keeps_owned_apps_drops_dlc_depots_without_keys() {
        // 模拟 TLOU: 主仓有 key, DLC 仓无 key — 只摘 depot, 保留 dlc app 所有权.
        let mut b = CatalogBundle {
            apps: vec![1888930, 2245260, 2254450],
            ..CatalogBundle::default()
        };
        b.app_depots
            .insert(1888930, vec![1888931, 2255770, 2290640]);
        b.depot_keys.insert(1888931, "ab".repeat(32));
        b.requires_token = Some(false);
        b.manifests.insert(
            1888931,
            stt_core::ManifestOverride {
                manifest_gid: 1,
                size: 10,
            },
        );
        b.manifests.insert(
            2255770,
            stt_core::ManifestOverride {
                manifest_gid: 2,
                size: 10,
            },
        );
        b.manifests.insert(
            2290640,
            stt_core::ManifestOverride {
                manifest_gid: 3,
                size: 10,
            },
        );

        let dropped = prune_keyless_depots(&mut b);
        assert_eq!(dropped, vec![2255770, 2290640]);
        assert_eq!(b.app_depots.get(&1888930), Some(&vec![1888931]));
        assert!(b.manifests.contains_key(&1888931));
        assert!(!b.manifests.contains_key(&2255770));
        assert_eq!(b.apps, vec![1888930, 2245260, 2254450]);

        let text = format_catalog_lua(1888930, &b);
        assert!(text.contains("addappid(2245260,"));
        assert!(text.contains("setappdepots(1888930, {1888931})"));
        assert!(!text.contains("2255770"));
        assert!(missing_download_data(1888930, &b).is_empty());
    }

    #[test]
    fn format_lua_skips_depots_without_valid_keys() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11, 12]);
        b.depot_keys.insert(12, "cd".repeat(32));
        let text = format_catalog_lua(42, &b);
        assert!(text.contains("addappid(12, 0,"));
        assert!(!text.contains("addappid(11,"));
    }

    #[test]
    fn write_manifest_blobs_writes_both_depotcache_dirs() {
        let root = tempfile::tempdir().unwrap();
        let blobs = vec![stt_catalog::ManifestBlob {
            depot_id: 43,
            manifest_gid: 99,
            bytes: b"raw-manifest".to_vec(),
        }];

        let written = write_manifest_blobs(root.path(), &blobs).unwrap();

        assert_eq!(written, 1);
        let name = manifest_file_name(43, 99);
        let primary = root.path().join("depotcache").join(&name);
        let secondary = root.path().join("config").join("depotcache").join(&name);
        assert_eq!(std::fs::read(primary).unwrap(), b"raw-manifest");
        assert_eq!(std::fs::read(secondary).unwrap(), b"raw-manifest");
    }

    #[test]
    fn write_manifest_blobs_skips_empty_and_zero_ids() {
        let root = tempfile::tempdir().unwrap();
        let blobs = vec![
            stt_catalog::ManifestBlob {
                depot_id: 0,
                manifest_gid: 99,
                bytes: b"x".to_vec(),
            },
            stt_catalog::ManifestBlob {
                depot_id: 43,
                manifest_gid: 0,
                bytes: b"x".to_vec(),
            },
            stt_catalog::ManifestBlob {
                depot_id: 43,
                manifest_gid: 99,
                bytes: Vec::new(),
            },
        ];

        assert_eq!(write_manifest_blobs(root.path(), &blobs).unwrap(), 0);
        assert!(!root
            .path()
            .join("depotcache")
            .join("43_99.manifest")
            .exists());
    }

    #[test]
    fn zero_token_counts_as_missing() {
        let mut b = CatalogBundle::default();
        b.apps.push(42);
        b.app_depots.insert(42, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        // 上游用 0 表示未收录 (CaiGames app_token: 0), 不能当"有 token".
        b.access_tokens.insert(42, 0);
        assert!(missing_download_data(42, &b).access_token);
    }

    #[cfg(feature = "lua")]
    #[test]
    fn remove_deletes_our_lua() {
        let (root, state, out) = add_app_42();
        let gone = remove_from_library(&state, root.path(), 42).unwrap();
        assert_eq!(gone.lua_path.as_ref(), Some(&out.lua_path));
        assert!(!out.lua_path.exists());
    }

    #[cfg(feature = "lua")]
    #[test]
    fn remove_drops_the_app_from_rules() {
        let (root, state, _out) = add_app_42();
        remove_from_library(&state, root.path(), 42).unwrap();
        assert!(!state.with_rules(|r: &AppRules| r.is_owned(42)));
    }

    /// 用户手写的 lua 不是我们写的, 移除一个 app 不该把它们一起弄没.
    #[cfg(feature = "lua")]
    #[test]
    fn remove_keeps_hand_written_lua() {
        let (root, state, _out) = add_app_42();
        let mine = default_lua_dir(root.path()).join("mine.lua");
        std::fs::write(&mine, "addappid(777)\n").unwrap();
        state.reload_lua_dirs(root.path());

        remove_from_library(&state, root.path(), 42).unwrap();
        assert!(mine.exists());
        assert!(state.with_rules(|r: &AppRules| r.is_owned(777)));
    }

    /// 已经不在了也算成功 —— 目的就是"让它不在".
    #[cfg(feature = "lua")]
    #[test]
    fn remove_is_idempotent() {
        let (root, state, _out) = add_app_42();
        remove_from_library(&state, root.path(), 42).unwrap();
        let again = remove_from_library(&state, root.path(), 42).unwrap();
        assert!(again.lua_path.is_none());
    }

    #[test]
    fn disabled_tool_errors() {
        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();
        let mut host = HostConfig::default();
        host.tools.enabled.insert("catalog_add".into(), false);
        state.apply_host(host);
        let provider = MockCatalogProvider::new().with_auto_generate(true);
        assert!(add_to_library(&state, root.path(), &provider, 1).is_err());
    }

    #[test]
    fn invalid_provider_data_is_rejected_before_write() {
        struct InvalidProvider;

        impl CatalogProvider for InvalidProvider {
            fn id(&self) -> &str {
                "invalid-test"
            }

            fn fetch(&self, app_id: AppId) -> CatalogResult<CatalogBundle> {
                Ok(CatalogBundle {
                    apps: vec![app_id],
                    depot_keys: std::collections::HashMap::from([(99, "bad".into())]),
                    ..CatalogBundle::default()
                })
            }
        }

        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();

        let error = add_to_library(&state, root.path(), &InvalidProvider, 42).unwrap_err();

        assert!(!catalog_lua_path(root.path(), 42).exists(), "{error}");
    }
}
