//! catalog_add: AddToLibrary 意图路径 (Mock/真源共用).

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use stt_catalog::{validate_bundle, CatalogProvider, CatalogTraceEntry};
use stt_core::{AppId, CatalogBundle};

use crate::error::{ConfigError, Result};
use crate::lua_load::default_lua_dir;
use crate::tools::ToolId;
use crate::ConfigState;

/// 一次入库意图的结果 (成功 = 元数据已进 core 且 lua 已落盘).
#[derive(Debug, Clone)]
pub struct AddToLibraryOutcome {
    pub app_id: AppId,
    pub provider_id: String,
    pub provider_trace: Vec<CatalogTraceEntry>,
    pub lua_path: PathBuf,
    pub epoch: u64,
    pub owned_count: usize,
}

/// 将 bundle 写成兼容上游的 lua 片段.
pub fn format_catalog_lua(app_id: AppId, bundle: &CatalogBundle) -> String {
    let mut out = String::from("-- generated by SteamTools catalog_add\n");
    let mut apps = bundle.apps.clone();
    apps.sort_unstable();
    apps.dedup();
    for id in apps {
        let purchase_time = bundle.purchase_times.get(&id).copied().unwrap_or(0);
        out.push_str(&format!("addappid({id}, {purchase_time})\n"));
    }

    let mut depots: Vec<_> = bundle
        .app_depots
        .values()
        .flatten()
        .copied()
        .collect();
    depots.sort_unstable();
    depots.dedup();
    for depot_id in depots {
        let key = bundle
            .depot_keys
            .get(&depot_id)
            .map(String::as_str)
            .unwrap_or_default();
        out.push_str(&format!("addappid({depot_id}, 0, \"{key}\")\n"));
    }
    let mut access_tokens: Vec<_> = bundle.access_tokens.iter().collect();
    access_tokens.sort_unstable_by_key(|(app_id, _)| **app_id);
    for (&id, &token) in access_tokens {
        out.push_str(&format!("addtoken({id}, \"{token}\")\n"));
    }
    let mut manifests: Vec<_> = bundle.manifests.iter().collect();
    manifests.sort_unstable_by_key(|(depot_id, _)| **depot_id);
    for (&depot, over) in manifests {
        out.push_str(&format!(
            "setmanifestid({depot}, \"{}\")\n",
            over.manifest_gid
        ));
    }
    let mut app_depots: Vec<_> = bundle.app_depots.iter().collect();
    app_depots.sort_unstable_by_key(|(id, _)| **id);
    for (&id, depots) in app_depots {
        let mut depots = depots.clone();
        depots.sort_unstable();
        depots.dedup();
        let values = depots
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "if type(setappdepots) == \"function\" then setappdepots({id}, {{{values}}}) end\n"
        ));
    }
    debug_assert!(bundle.apps.contains(&app_id));
    out
}

pub fn catalog_lua_path(steam_root: &Path, app_id: AppId) -> PathBuf {
    default_lua_dir(steam_root).join(format!("stt_{app_id}.lua"))
}

/// 写入 `<Steam>/config/lua/stt_{app_id}.lua`.
pub fn write_catalog_lua(
    steam_root: &Path,
    app_id: AppId,
    bundle: &CatalogBundle,
) -> Result<PathBuf> {
    let dir = default_lua_dir(steam_root);
    std::fs::create_dir_all(&dir).map_err(|source| ConfigError::Io {
        path: dir.clone(),
        source,
    })?;
    let path = catalog_lua_path(steam_root, app_id);
    let body = format_catalog_lua(app_id, bundle);
    crate::intent::write_atomic(&path, &body)?;
    Ok(path)
}

fn now_unix() -> u32 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .ok()
        .and_then(|d| u32::try_from(d.as_secs()).ok())
        .unwrap_or(0)
}

/// 工具开启时: fetch → 写 lua → 合并进 ConfigState.
pub fn add_to_library(
    state: &ConfigState,
    steam_root: &Path,
    provider: &dyn CatalogProvider,
    app_id: AppId,
) -> Result<AddToLibraryOutcome> {
    if !state.tools().is_enabled(ToolId::CatalogAdd) {
        return Err(ConfigError::Invalid("catalog_add tool is disabled".into()));
    }

    let fetched = provider.fetch_with_trace(app_id)?;
    let mut bundle = validate_bundle(app_id, fetched.bundle)?;
    bundle.purchase_times.entry(app_id).or_insert_with(now_unix);

    let lua_path = write_catalog_lua(steam_root, app_id, &bundle)?;

    state.with_rules_mut(|rules| {
        rules.apply_catalog_bundle(&bundle);
    });

    // 再读一遍刚写的 lua, 与扫盘语义对齐 (可选但有助于发现写坏的脚本).
    let text = std::fs::read_to_string(&lua_path).map_err(|source| ConfigError::Io {
        path: lua_path.clone(),
        source,
    })?;
    state.apply_lua(&text)?;

    Ok(AddToLibraryOutcome {
        app_id,
        provider_id: fetched.source,
        provider_trace: fetched.trace,
        lua_path,
        epoch: state.rules_epoch(),
        owned_count: state.owned_count(),
    })
}

/// 一次移除的结果.
#[derive(Debug, Clone)]
pub struct RemoveFromLibraryOutcome {
    pub app_id: AppId,
    /// 删掉的 lua; 文件本来就不在时为 `None` (仍算成功).
    pub lua_path: Option<PathBuf>,
    pub epoch: u64,
    pub owned_count: usize,
}

/// 把入库撤掉: 删 `stt_{app_id}.lua`, 然后整表重扫.
///
/// 不去 `AppRules` 里做减法 —— 那份状态是所有 lua 合并出来的, 单独摘一个 app 容易
/// 与磁盘不一致. 删完重扫是唯一能保证两边一致的做法, 而且几十个文件也就几毫秒.
///
/// 只删我们自己写的那个文件; 用户手写的 lua 一概不碰.
#[cfg(feature = "lua")]
pub fn remove_from_library(
    state: &ConfigState,
    steam_root: &Path,
    app_id: AppId,
) -> Result<RemoveFromLibraryOutcome> {
    let path = catalog_lua_path(steam_root, app_id);
    let lua_path = match std::fs::remove_file(&path) {
        Ok(()) => Some(path),
        // 已经不在了: 目的已经达到, 不当错误.
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(ConfigError::Io {
                path: path.clone(),
                source,
            })
        }
    };
    state.reload_lua_dirs(steam_root);
    Ok(RemoveFromLibraryOutcome {
        app_id,
        lua_path,
        epoch: state.rules_epoch(),
        owned_count: state.owned_count(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host_toml::HostConfig;
    use stt_catalog::{CatalogResult, MockCatalogProvider};
    use stt_core::AppRules;

    #[test]
    fn format_lua_contains_addappid_and_key() {
        let mut b = CatalogBundle::default();
        b.apps.push(10);
        b.app_depots.insert(10, vec![11]);
        b.depot_keys.insert(11, "a".repeat(64));
        b.manifests.insert(
            11,
            stt_core::ManifestOverride {
                manifest_gid: 99,
                size: 0,
            },
        );
        let s = format_catalog_lua(10, &b);
        assert!(s.contains("addappid(11, 0,"));
        assert!(s.contains("setappdepots(10, {11})"));
        assert!(s.contains("setmanifestid(11, \"99\")\n"));
    }

    /// 默认工具开关下跑一次入库 (tempdir 需与结果同生命周期).
    fn add_app_42() -> (tempfile::TempDir, ConfigState, AddToLibraryOutcome) {
        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();
        let provider = MockCatalogProvider::new()
            .with_auto_generate(true)
            .with_simple_app(42, 43, &"ab".repeat(32), 100);
        let out = add_to_library(&state, root.path(), &provider, 42).unwrap();
        (root, state, out)
    }

    #[test]
    fn writes_lua_with_addappid_line() {
        let (_root, _state, out) = add_app_42();
        let text = std::fs::read_to_string(&out.lua_path).unwrap();
        assert!(text.contains("addappid(42,"), "lua 缺 addappid: {text}");
    }

    #[test]
    fn replaces_existing_lua_atomically_without_leaving_temp_file() {
        let root = tempfile::tempdir().unwrap();
        let path = catalog_lua_path(root.path(), 42);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "old").unwrap();
        let provider = MockCatalogProvider::new()
            .with_auto_generate(true)
            .with_simple_app(42, 43, &"ab".repeat(32), 100);
        let state = ConfigState::new();

        add_to_library(&state, root.path(), &provider, 42).unwrap();

        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("addappid(42,"), "{text}");
        assert!(!path.with_file_name("stt_42.lua.tmp").exists());
    }

    #[test]
    fn marks_app_owned_in_rules() {
        let (_root, state, _out) = add_app_42();
        assert!(state.with_rules(|r: &AppRules| r.is_owned(42)));
        assert!(!state.with_rules(|r: &AppRules| r.is_owned(43)));
    }

    #[test]
    fn keeps_depot_key_from_provider() {
        let (_root, state, _out) = add_app_42();
        assert_eq!(
            state.with_rules(|r: &AppRules| r.depot_key(43).map(str::len)),
            Some(64)
        );
    }

    #[test]
    fn writes_depot_key_with_depot_id() {
        let (_root, _state, out) = add_app_42();
        let text = std::fs::read_to_string(out.lua_path).unwrap();

        assert!(
            text.contains("addappid(43, 0,"),
            "lua 没按 DepotId 写 key: {text}"
        );
    }

    #[test]
    fn lua_round_trip_preserves_app_depot_relationship() {
        let (_root, state, _out) = add_app_42();

        assert_eq!(state.with_rules(|rules| rules.app_depots(42).to_vec()), vec![43]);
    }

    #[test]
    fn format_lua_orders_metadata_by_id() {
        let mut bundle = CatalogBundle::default();
        bundle.apps.push(42);
        bundle.app_depots.insert(42, vec![44, 43]);
        bundle.depot_keys.insert(44, "cd".repeat(32));
        bundle.depot_keys.insert(43, "ab".repeat(32));

        let text = format_catalog_lua(42, &bundle);

        assert!(text.find("addappid(43, 0,") < text.find("addappid(44, 0,"));
    }

    #[test]
    fn bumps_rules_epoch() {
        let (_root, _state, out) = add_app_42();
        assert!(out.epoch > 0);
    }

    #[cfg(feature = "lua")]
    #[test]
    fn remove_deletes_our_lua() {
        let (root, state, out) = add_app_42();
        let gone = remove_from_library(&state, root.path(), 42).unwrap();
        assert_eq!(gone.lua_path.as_ref(), Some(&out.lua_path));
        assert!(!out.lua_path.exists());
    }

    #[cfg(feature = "lua")]
    #[test]
    fn remove_drops_the_app_from_rules() {
        let (root, state, _out) = add_app_42();
        remove_from_library(&state, root.path(), 42).unwrap();
        assert!(!state.with_rules(|r: &AppRules| r.is_owned(42)));
    }

    /// 用户手写的 lua 不是我们写的, 移除一个 app 不该把它们一起弄没.
    #[cfg(feature = "lua")]
    #[test]
    fn remove_keeps_hand_written_lua() {
        let (root, state, _out) = add_app_42();
        let mine = default_lua_dir(root.path()).join("mine.lua");
        std::fs::write(&mine, "addappid(777)\n").unwrap();
        state.reload_lua_dirs(root.path());

        remove_from_library(&state, root.path(), 42).unwrap();
        assert!(mine.exists());
        assert!(state.with_rules(|r: &AppRules| r.is_owned(777)));
    }

    /// 已经不在了也算成功 —— 目的就是"让它不在".
    #[cfg(feature = "lua")]
    #[test]
    fn remove_is_idempotent() {
        let (root, state, _out) = add_app_42();
        remove_from_library(&state, root.path(), 42).unwrap();
        let again = remove_from_library(&state, root.path(), 42).unwrap();
        assert!(again.lua_path.is_none());
    }

    #[test]
    fn disabled_tool_errors() {
        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();
        let mut host = HostConfig::default();
        host.tools.enabled.insert("catalog_add".into(), false);
        state.apply_host(host);
        let provider = MockCatalogProvider::new().with_auto_generate(true);
        assert!(add_to_library(&state, root.path(), &provider, 1).is_err());
    }

    #[test]
    fn invalid_provider_data_is_rejected_before_write() {
        struct InvalidProvider;

        impl CatalogProvider for InvalidProvider {
            fn id(&self) -> &str {
                "invalid-test"
            }

            fn fetch(&self, app_id: AppId) -> CatalogResult<CatalogBundle> {
                Ok(CatalogBundle {
                    apps: vec![app_id],
                    depot_keys: std::collections::HashMap::from([(99, "bad".into())]),
                    ..CatalogBundle::default()
                })
            }
        }

        let root = tempfile::tempdir().unwrap();
        let state = ConfigState::new();

        let error = add_to_library(&state, root.path(), &InvalidProvider, 42).unwrap_err();

        assert!(!catalog_lua_path(root.path(), 42).exists(), "{error}");
    }
}
