[package]
name = "stt-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "SteamTools host cdylib (SteamTools.dll)"

[lib]
# Product DLL filename on disk.
crate-type = ["cdylib", "rlib"]
name = "SteamTools"

[lints.rust]
non_snake_case = "allow"

[dependencies]
stt-core = { workspace = true }
stt-platform = { workspace = true }
stt-config = { workspace = true }
stt-metadata = { workspace = true }
stt-hook = { workspace = true }
